### ISSUE TITLE
help，I just can't    folds.csv

### ISSUE THREAD

**Issue by cy0616** [killthekitten/kaggle-carvana-2017#7]
I gonna run your code,but I can't find the folds.csv neither in this github repo nor in the kaggle-carvana-2017 competition.
It's so great if you could tell me where to find it,or you can send it to my email~
This is my email: cy450444174@gmail.com 
Thanks anyway!

**Comment by killthekitten** [comment]
Hey @cy0616,

Thanks for spotting this! Any file of the following format will do: 

```csv
id,fold
424658d9f222,2
```

The columns should respectively contain a car id and a fold number. Important to notice:
1. We had 5 of them to do 5-fold cross-validation. 
2. Since the cars were of a different size and colors, it was critical to keep each of 16 pictures of a single car in the same fold. 
3. Folds were created by sorting by the size of masks (i.e. total number of 1s vs 0s in the mask, a simple sum over the mask matrix).
